# Generated by Django 4.2.16 on 2025-01-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_hobby_tag_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
