# Generated by Django 4.2.16 on 2025-01-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='trending',
            field=models.CharField(default=' ', max_length=30, null=True),
        ),
    ]
