# Generated by Django 4.2.16 on 2025-01-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_tag_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='trending',
        ),
    ]
